// Code generated by make generate-metadata; DO NOT EDIT.
// Source of truth: cli-metadata.yaml plus input-schema.yaml/output-schema.yaml.
// The generator compiles provider/tool metadata and JSON schemas into static Go values for the factory binary.

package googleworkspace

import "cli-factory/internal/provider"

const providerID = "google-workspace"

const providerName = "Google Workspace"

const providerShortDescription = "Use Gmail and Google Calendar from a Google Workspace account."

const providerLongDescription = "Google Workspace exposes curated Gmail and Google Calendar workflows for agents: send and check email, and create and check calendar events with OAuth-backed API access."

var providerCategories = []string{"email", "calendar", "productivity"}

var providerAliases = []string{"google", "gmail", "calendar"}

var providerParameters = []provider.Parameter{
	{Name: "access_token", Description: "Google OAuth 2.0 access token with Gmail and Calendar scopes.", Required: true, Secret: true},
	{Name: "user_id", Description: "Gmail user identifier. Defaults to me.", Required: false, Secret: false},
	{Name: "calendar_id", Description: "Google Calendar ID. Defaults to primary.", Required: false, Secret: false},
}
