package docgen

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

const generatedNotice = "<!-- This page is generated by `make generate-docs`. Edit provider metadata and schemas instead. -->"

type ProviderDoc struct {
	ID               string
	Name             string
	ShortDescription string
	LongDescription  string
	Categories       []string
	Aliases          []string
	Parameters       []ParamDoc
	Tools            []ToolDoc
}

type ToolDoc struct {
	ID               string
	Name             string
	ShortDescription string
	LongDescription  string
	Categories       []string
	Aliases          []string
	CommandPath      []string
	InputParams      []string
	OutputFields     []string
	InputSchema      string
	OutputSchema     string
}

type ParamDoc struct {
	Name        string
	Description string
}

type Options struct {
	SourceRoot string
	DocsRoot   string
}

func Generate(root string) error {
	return GenerateTo(Options{SourceRoot: root, DocsRoot: root})
}

func GenerateTo(opts Options) error {
	if opts.SourceRoot == "" {
		opts.SourceRoot = "."
	}
	if opts.DocsRoot == "" {
		opts.DocsRoot = opts.SourceRoot
	}
	providers, err := LoadProviders(opts.SourceRoot)
	if err != nil {
		return err
	}
	if err := writeProjectDocs(opts.DocsRoot, providers); err != nil {
		return err
	}
	return updateMintlifyConfig(opts.DocsRoot, providers)
}

func LoadProviders(root string) ([]ProviderDoc, error) {
	providersDir := filepath.Join(root, "providers")
	entries, err := os.ReadDir(providersDir)
	if os.IsNotExist(err) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}

	var providers []ProviderDoc
	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}
		providerDir := filepath.Join(providersDir, entry.Name())
		metaPath := filepath.Join(providerDir, "cli-metadata.yaml")
		if !fileExists(metaPath) {
			continue
		}
		meta, err := readYAMLMap(metaPath)
		if err != nil {
			return nil, fmt.Errorf("read provider metadata %s: %w", metaPath, err)
		}
		provider := ProviderDoc{
			ID:               firstString(meta, entry.Name(), "id", "provider_id"),
			Name:             firstString(meta, titleFromID(entry.Name()), "name", "title"),
			ShortDescription: firstString(meta, "", "short_description", "description"),
			LongDescription:  firstString(meta, "", "long_description", "documentation"),
			Categories:       stringSlice(meta["categories"]),
			Aliases:          stringSlice(meta["aliases"]),
			Parameters:       paramDocs(meta["provider_parameters"], meta["parameters"]),
		}
		tools, err := loadTools(providerDir, provider.ID)
		if err != nil {
			return nil, err
		}
		provider.Tools = tools
		providers = append(providers, provider)
	}
	sort.Slice(providers, func(i, j int) bool { return providers[i].ID < providers[j].ID })
	return providers, nil
}

func loadTools(providerDir, providerID string) ([]ToolDoc, error) {
	entries, err := os.ReadDir(providerDir)
	if err != nil {
		return nil, err
	}
	var tools []ToolDoc
	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}
		toolDir := filepath.Join(providerDir, entry.Name())
		metaPath := filepath.Join(toolDir, "cli-metadata.yaml")
		if !fileExists(metaPath) {
			continue
		}
		meta, err := readYAMLMap(metaPath)
		if err != nil {
			return nil, fmt.Errorf("read tool metadata %s: %w", metaPath, err)
		}
		inputSchema := readOptional(filepath.Join(toolDir, "input-schema.yaml"))
		outputSchema := readOptional(filepath.Join(toolDir, "output-schema.yaml"))
		tool := ToolDoc{
			ID:               firstString(meta, entry.Name(), "id", "tool_id"),
			Name:             firstString(meta, titleFromID(entry.Name()), "name", "title"),
			ShortDescription: firstString(meta, "", "short_description", "description"),
			LongDescription:  firstString(meta, "", "long_description", "documentation"),
			Categories:       stringSlice(meta["categories"]),
			Aliases:          stringSlice(meta["aliases"]),
			CommandPath:      stringSlice(meta["command_path"]),
			InputParams:      schemaPropertyNames(inputSchema),
			OutputFields:     schemaPropertyNames(outputSchema),
			InputSchema:      inputSchema,
			OutputSchema:     outputSchema,
		}
		if len(tool.CommandPath) == 0 {
			tool.CommandPath = []string{providerID, tool.ID}
		}
		tools = append(tools, tool)
	}
	sort.Slice(tools, func(i, j int) bool { return tools[i].ID < tools[j].ID })
	return tools, nil
}

func writeProjectDocs(root string, providers []ProviderDoc) error {
	projectDir := filepath.Join(root, "projects", "cli-factory")
	if err := os.MkdirAll(projectDir, 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(projectDir, "index.mdx"), []byte(renderProjectIndex()), 0o644); err != nil {
		return err
	}
	overviewPath := filepath.Join(projectDir, "providers", "overview.mdx")
	if err := os.MkdirAll(filepath.Dir(overviewPath), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(overviewPath, []byte(renderProvidersOverview(providers)), 0o644); err != nil {
		return err
	}
	for _, provider := range providers {
		providerDocsDir := filepath.Join(projectDir, "providers", provider.ID)
		if err := os.MkdirAll(filepath.Join(providerDocsDir, "tools"), 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(filepath.Join(providerDocsDir, "index.mdx"), []byte(renderProvider(provider)), 0o644); err != nil {
			return err
		}
		for _, tool := range provider.Tools {
			path := filepath.Join(providerDocsDir, "tools", tool.ID+".mdx")
			if err := os.WriteFile(path, []byte(renderTool(provider, tool)), 0o644); err != nil {
				return err
			}
		}
	}
	return nil
}

func renderProjectIndex() string {
	return "---\n" +
		"title: CLI Factory\n" +
		"description: Agent-first CLI provider and tool documentation.\n" +
		"sidebarTitle: CLI Factory\n" +
		"---\n\n" +
		"<!-- This page is generated by `make generate-docs`. Edit cli-factory provider metadata and schemas instead. -->\n\n" +
		"# CLI Factory\n\n" +
		"CLI Factory builds a single `factory` binary for AI agents to discover and invoke curated provider tools.\n\n" +
		"## Sections\n\n" +
		"- [Providers](./providers/overview): generated provider and tool reference.\n"
}

func renderProvidersOverview(providers []ProviderDoc) string {
	var b strings.Builder
	b.WriteString("---\ntitle: Providers\ndescription: CLI Factory providers and tools.\nsidebarTitle: Providers\n---\n\n")
	b.WriteString("<!-- This page is generated by `make generate-docs`. Edit cli-factory provider metadata and schemas instead. -->\n\n")
	b.WriteString("# Providers\n\n")
	if len(providers) == 0 {
		b.WriteString("No providers have been generated yet.\n")
		return b.String()
	}
	for _, provider := range providers {
		fmt.Fprintf(&b, "- [%s](./%s): %s\n", provider.Name, provider.ID, provider.ShortDescription)
	}
	b.WriteString("\n")
	return b.String()
}

func renderProvider(provider ProviderDoc) string {
	var b strings.Builder
	fmt.Fprintf(&b, "---\ntitle: %s\ndescription: %s\nsidebarTitle: %s\n---\n\n", escapeFrontmatter(provider.Name), escapeFrontmatter(provider.ShortDescription), escapeFrontmatter(provider.Name))
	fmt.Fprintf(&b, "%s\n\n# %s\n\n", generatedNotice, provider.Name)
	writeParagraph(&b, provider.LongDescription, provider.ShortDescription)
	writeCSVSection(&b, "Categories", provider.Categories)
	writeCSVSection(&b, "Aliases", provider.Aliases)
	if len(provider.Parameters) > 0 {
		b.WriteString("## Provider Parameters\n\n")
		for _, param := range provider.Parameters {
			if param.Description == "" {
				fmt.Fprintf(&b, "- `%s`\n", param.Name)
			} else {
				fmt.Fprintf(&b, "- `%s`: %s\n", param.Name, param.Description)
			}
		}
		b.WriteString("\n")
	}
	if len(provider.Tools) > 0 {
		b.WriteString("## Tools\n\n")
		for _, tool := range provider.Tools {
			fmt.Fprintf(&b, "- [%s](./tools/%s): %s\n", tool.Name, tool.ID, tool.ShortDescription)
		}
		b.WriteString("\n")
	}
	return b.String()
}

func renderTool(provider ProviderDoc, tool ToolDoc) string {
	var b strings.Builder
	fmt.Fprintf(&b, "---\ntitle: %s\ndescription: %s\nsidebarTitle: %s\n---\n\n", escapeFrontmatter(tool.Name), escapeFrontmatter(tool.ShortDescription), escapeFrontmatter(tool.Name))
	fmt.Fprintf(&b, "%s\n\n# %s\n\n", generatedNotice, tool.Name)
	fmt.Fprintf(&b, "**Provider:** [%s](../index)\n\n", provider.Name)
	writeParagraph(&b, tool.LongDescription, tool.ShortDescription)
	writeCSVSection(&b, "Command Path", tool.CommandPath)
	writeCSVSection(&b, "Categories", tool.Categories)
	writeCSVSection(&b, "Aliases", tool.Aliases)
	writeParamNameSection(&b, "Provider Parameters", provider.Parameters)
	writeCSVSection(&b, "Input Parameters", tool.InputParams)
	writeCSVSection(&b, "Output Fields", tool.OutputFields)
	writeSchemaSection(&b, "Input Schema", tool.InputSchema)
	writeSchemaSection(&b, "Output Schema", tool.OutputSchema)
	return b.String()
}

func updateMintlifyConfig(root string, providers []ProviderDoc) error {
	configPath := filepath.Join(root, "docs.json")
	config := map[string]any{}
	if data, err := os.ReadFile(configPath); err == nil {
		if err := json.Unmarshal(data, &config); err != nil {
			return fmt.Errorf("read docs.json: %w", err)
		}
	} else if os.IsNotExist(err) {
		config = map[string]any{
			"$schema": "https://mintlify.com/docs.json",
			"name":    "Tilde Docs",
			"theme":   "mint",
		}
	} else {
		return err
	}

	providerPages := []any{"projects/cli-factory/providers/overview"}
	for _, provider := range providers {
		pages := []any{"projects/cli-factory/providers/" + provider.ID + "/index"}
		if len(provider.Tools) > 0 {
			toolPages := make([]any, 0, len(provider.Tools))
			for _, tool := range provider.Tools {
				toolPages = append(toolPages, "projects/cli-factory/providers/"+provider.ID+"/tools/"+tool.ID)
			}
			pages = append(pages, map[string]any{
				"group":    "Tools",
				"expanded": true,
				"pages":    toolPages,
			})
		}
		providerPages = append(providerPages, map[string]any{
			"group": provider.Name,
			"root":  "projects/cli-factory/providers/" + provider.ID + "/index",
			"pages": pages,
		})
	}
	cliFactoryGroup := map[string]any{
		"group": "CLI Factory",
		"root":  "projects/cli-factory/index",
		"pages": []any{
			"projects/cli-factory/index",
			map[string]any{
				"group": "Providers",
				"root":  "projects/cli-factory/providers/overview",
				"pages": providerPages,
			},
		},
	}

	navigation := ensureMap(config, "navigation")
	tabs := anySlice(navigation["tabs"])
	projectsTab := findNamedMap(tabs, "tab", "Projects")
	if projectsTab == nil {
		projectsTab = map[string]any{"tab": "Projects"}
		tabs = append(tabs, projectsTab)
	}
	groups := anySlice(projectsTab["groups"])
	groups = replaceNamedMap(groups, "group", "CLI Factory", cliFactoryGroup)
	projectsTab["groups"] = groups
	navigation["tabs"] = tabs
	config["navigation"] = navigation

	data, err := json.MarshalIndent(config, "", "  ")
	if err != nil {
		return err
	}
	data = append(data, '\n')
	return os.WriteFile(filepath.Join(root, "docs.json"), data, 0o644)
}

func ensureMap(parent map[string]any, key string) map[string]any {
	if value, ok := parent[key].(map[string]any); ok {
		return value
	}
	value := map[string]any{}
	parent[key] = value
	return value
}

func anySlice(value any) []any {
	if value == nil {
		return nil
	}
	if out, ok := value.([]any); ok {
		return out
	}
	return nil
}

func findNamedMap(items []any, key, name string) map[string]any {
	for _, item := range items {
		m, ok := item.(map[string]any)
		if !ok {
			continue
		}
		if m[key] == name {
			return m
		}
	}
	return nil
}

func replaceNamedMap(items []any, key, name string, replacement map[string]any) []any {
	for i, item := range items {
		m, ok := item.(map[string]any)
		if ok && m[key] == name {
			items[i] = replacement
			return items
		}
	}
	return append(items, replacement)
}

func writeParagraph(b *strings.Builder, primary, fallback string) {
	text := strings.TrimSpace(primary)
	if text == "" {
		text = strings.TrimSpace(fallback)
	}
	if text != "" {
		b.WriteString(text)
		b.WriteString("\n\n")
	}
}

func writeCSVSection(b *strings.Builder, title string, values []string) {
	if len(values) == 0 {
		return
	}
	fmt.Fprintf(b, "## %s\n\n%s\n\n", title, strings.Join(values, ", "))
}

func writeParamNameSection(b *strings.Builder, title string, values []ParamDoc) {
	if len(values) == 0 {
		return
	}
	names := make([]string, 0, len(values))
	for _, value := range values {
		names = append(names, value.Name)
	}
	writeCSVSection(b, title, names)
}

func writeSchemaSection(b *strings.Builder, title, schema string) {
	if strings.TrimSpace(schema) == "" {
		return
	}
	fmt.Fprintf(b, "## %s\n\n```yaml\n%s\n```\n\n", title, strings.TrimSpace(schema))
}

func readYAMLMap(path string) (map[string]any, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var out map[string]any
	if err := yaml.Unmarshal(data, &out); err != nil {
		return nil, err
	}
	if out == nil {
		out = map[string]any{}
	}
	return out, nil
}

func readOptional(path string) string {
	data, err := os.ReadFile(path)
	if err != nil {
		return ""
	}
	return string(data)
}

func firstString(meta map[string]any, fallback string, keys ...string) string {
	for _, key := range keys {
		if value, ok := meta[key]; ok {
			if s, ok := value.(string); ok && strings.TrimSpace(s) != "" {
				return strings.TrimSpace(s)
			}
		}
	}
	return fallback
}

func stringSlice(value any) []string {
	var out []string
	switch v := value.(type) {
	case []any:
		for _, item := range v {
			if s, ok := item.(string); ok && strings.TrimSpace(s) != "" {
				out = append(out, strings.TrimSpace(s))
			}
		}
	case []string:
		for _, item := range v {
			if strings.TrimSpace(item) != "" {
				out = append(out, strings.TrimSpace(item))
			}
		}
	case string:
		if strings.TrimSpace(v) != "" {
			out = append(out, strings.TrimSpace(v))
		}
	}
	return out
}

func paramDocs(values ...any) []ParamDoc {
	for _, value := range values {
		if params := parseParamDocs(value); len(params) > 0 {
			return params
		}
	}
	return nil
}

func parseParamDocs(value any) []ParamDoc {
	var out []ParamDoc
	items, ok := value.([]any)
	if !ok {
		return nil
	}
	for _, item := range items {
		switch v := item.(type) {
		case string:
			out = append(out, ParamDoc{Name: v})
		case map[string]any:
			name := firstString(v, "", "name", "id")
			if name != "" {
				out = append(out, ParamDoc{Name: name, Description: firstString(v, "", "description")})
			}
		}
	}
	return out
}

func schemaPropertyNames(raw string) []string {
	var meta map[string]any
	if err := yaml.Unmarshal([]byte(raw), &meta); err != nil {
		return nil
	}
	properties, ok := meta["properties"].(map[string]any)
	if !ok {
		return nil
	}
	names := make([]string, 0, len(properties))
	for name := range properties {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

func escapeFrontmatter(value string) string {
	value = strings.ReplaceAll(value, "\n", " ")
	value = strings.ReplaceAll(value, "\"", "'")
	if strings.TrimSpace(value) == "" {
		return "Generated documentation"
	}
	return value
}

func titleFromID(id string) string {
	parts := strings.FieldsFunc(id, func(r rune) bool { return r == '-' || r == '_' })
	for i, part := range parts {
		if part == "" {
			continue
		}
		parts[i] = strings.ToUpper(part[:1]) + part[1:]
	}
	return strings.Join(parts, " ")
}

func fileExists(path string) bool {
	info, err := os.Stat(path)
	return err == nil && !info.IsDir()
}

func NormalizeMDXForTest(value string) string {
	return string(bytes.TrimSpace([]byte(value)))
}
