// Code generated by make generate-metadata; DO NOT EDIT.
// Source of truth: cli-metadata.yaml plus input-schema.yaml/output-schema.yaml.
// The generator compiles provider/tool metadata and JSON schemas into static Go values for the factory binary.

package gmailcheck

import "cli-factory/internal/schema"

const toolID = "gmail-check"

const toolName = "Gmail Check"

const toolShortDescription = "Search recent Gmail messages."

const toolLongDescription = "Search or list Gmail messages for the authenticated Google Workspace user and return compact message details."

var toolCategories = []string{"email", "gmail", "search"}

var toolAliases = []string{"check-email", "search-email"}

var toolCommandPath = []string{"google-workspace", "gmail-check"}

var toolInputSchema = schema.JSONSchema(map[string]any{"properties": map[string]any{"include_snippet": map[string]any{"default": true, "type": "boolean"}, "max_results": map[string]any{"default": 10, "maximum": 25, "minimum": 1, "type": "integer"}, "query": map[string]any{"description": "Gmail search query.", "type": "string"}}, "type": "object"})

var toolOutputSchema = schema.JSONSchema(map[string]any{"properties": map[string]any{"messages": map[string]any{"items": map[string]any{"properties": map[string]any{"id": map[string]any{"type": "string"}, "label_ids": map[string]any{"items": map[string]any{"type": "string"}, "type": "array"}, "snippet": map[string]any{"type": "string"}, "thread_id": map[string]any{"type": "string"}}, "type": "object"}, "type": "array"}, "result_count": map[string]any{"type": "integer"}}, "type": "object"})
