// Code generated by make generate-metadata; DO NOT EDIT.
// Source of truth: cli-metadata.yaml plus input-schema.yaml/output-schema.yaml.
// The generator compiles provider/tool metadata and JSON schemas into static Go values for the factory binary.

package gmailsend

import "cli-factory/internal/schema"

const toolID = "gmail-send"

const toolName = "Gmail Send"

const toolShortDescription = "Send a Gmail message from a Google Workspace account."

const toolLongDescription = "Send a plain-text Gmail message through the Gmail API using OAuth-backed Google Workspace credentials."

var toolCategories = []string{"email", "gmail"}

var toolAliases = []string{"send-email", "email"}

var toolCommandPath = []string{"google-workspace", "gmail-send"}

var toolInputSchema = schema.JSONSchema(map[string]any{"properties": map[string]any{"bcc": map[string]any{"description": "Optional BCC recipients.", "items": map[string]any{"type": "string"}, "type": "array"}, "body_text": map[string]any{"minLength": 1, "type": "string"}, "cc": map[string]any{"description": "Optional CC recipients.", "items": map[string]any{"type": "string"}, "type": "array"}, "subject": map[string]any{"minLength": 1, "type": "string"}, "to": map[string]any{"description": "Recipient email addresses.", "items": map[string]any{"type": "string"}, "minItems": 1, "type": "array"}}, "required": []any{"to", "subject", "body_text"}, "type": "object"})

var toolOutputSchema = schema.JSONSchema(map[string]any{"properties": map[string]any{"label_ids": map[string]any{"items": map[string]any{"type": "string"}, "type": "array"}, "message_id": map[string]any{"type": "string"}, "thread_id": map[string]any{"type": "string"}}, "type": "object"})
