// Code generated by make generate-metadata; DO NOT EDIT.
// Source of truth: cli-metadata.yaml plus input-schema.yaml/output-schema.yaml.
// The generator compiles provider/tool metadata and JSON schemas into static Go values for the factory binary.

package example

import "cli-factory/internal/provider"

const providerID = "example"

const providerName = "Example"

const providerShortDescription = "Example provider for validating CLI Factory behavior."

const providerLongDescription = "The Example provider contains local non-network tools used to validate command routing, discovery, invocation logging, docs generation, and e2e tests."

var providerCategories = []string{"example", "debug"}

var providerAliases = []string{"sample", "test"}

var providerParameters = []provider.Parameter{
	{Name: "base_url", Description: "Optional base URL used by providers that proxy requests.", Required: false, Secret: false},
	{Name: "bearer_token", Description: "Optional bearer token for providers that need API auth.", Required: false, Secret: true},
}
