// Code generated by make generate-metadata; DO NOT EDIT.
// Source of truth: cli-metadata.yaml plus input-schema.yaml/output-schema.yaml.
// The generator compiles provider/tool metadata and JSON schemas into static Go values for the factory binary.

package echo

import "cli-factory/internal/schema"

const toolID = "echo"

const toolName = "Echo"

const toolShortDescription = "Echo a message for CLI and e2e validation."

const toolLongDescription = "Echo returns the provided message and is intentionally local, deterministic, and safe for CI e2e tests."

var toolCategories = []string{"example", "debug"}

var toolAliases = []string{"repeat", "say"}

var toolCommandPath = []string{"example", "echo"}

var toolInputSchema = schema.JSONSchema(map[string]any{"properties": map[string]any{"message": map[string]any{"description": "Message to echo.", "type": "string"}}, "required": []any{"message"}, "type": "object"})

var toolOutputSchema = schema.JSONSchema(map[string]any{"properties": map[string]any{"message": map[string]any{"description": "Echoed message.", "type": "string"}}, "type": "object"})
