// Code generated by make generate-metadata; DO NOT EDIT.
// Source of truth: cli-metadata.yaml plus input-schema.yaml/output-schema.yaml.
// The generator compiles provider/tool metadata and JSON schemas into static Go values for the factory binary.

package calendarcheck

import "cli-factory/internal/schema"

const toolID = "calendar-check"

const toolName = "Calendar Check"

const toolShortDescription = "Search Google Calendar events."

const toolLongDescription = "List or search Google Calendar events in a time window on the configured calendar."

var toolCategories = []string{"calendar", "scheduling", "search"}

var toolAliases = []string{"check-events", "list-events"}

var toolCommandPath = []string{"google-workspace", "calendar-check"}

var toolInputSchema = schema.JSONSchema(map[string]any{"properties": map[string]any{"max_results": map[string]any{"default": 10, "maximum": 50, "minimum": 1, "type": "integer"}, "query": map[string]any{"type": "string"}, "single_events": map[string]any{"default": true, "type": "boolean"}, "time_max": map[string]any{"format": "date-time", "type": "string"}, "time_min": map[string]any{"format": "date-time", "type": "string"}}, "required": []any{"time_min", "time_max"}, "type": "object"})

var toolOutputSchema = schema.JSONSchema(map[string]any{"properties": map[string]any{"events": map[string]any{"items": map[string]any{"properties": map[string]any{"end": map[string]any{"type": "string"}, "event_id": map[string]any{"type": "string"}, "html_link": map[string]any{"type": "string"}, "location": map[string]any{"type": "string"}, "start": map[string]any{"type": "string"}, "status": map[string]any{"type": "string"}, "summary": map[string]any{"type": "string"}}, "type": "object"}, "type": "array"}, "next_page_token": map[string]any{"type": "string"}, "result_count": map[string]any{"type": "integer"}}, "type": "object"})
