// Code generated by make generate-metadata; DO NOT EDIT.
// Source of truth: cli-metadata.yaml plus input-schema.yaml/output-schema.yaml.
// The generator compiles provider/tool metadata and JSON schemas into static Go values for the factory binary.

package calendarcreate

import "cli-factory/internal/schema"

const toolID = "calendar-create"

const toolName = "Calendar Create"

const toolShortDescription = "Create a Google Calendar event."

const toolLongDescription = "Create a Google Calendar event on the configured calendar and return compact event details."

var toolCategories = []string{"calendar", "scheduling"}

var toolAliases = []string{"create-event", "schedule"}

var toolCommandPath = []string{"google-workspace", "calendar-create"}

var toolInputSchema = schema.JSONSchema(map[string]any{"properties": map[string]any{"attendees": map[string]any{"items": map[string]any{"properties": map[string]any{"display_name": map[string]any{"type": "string"}, "email": map[string]any{"type": "string"}}, "required": []any{"email"}, "type": "object"}, "type": "array"}, "description": map[string]any{"type": "string"}, "end": map[string]any{"description": "RFC3339 end timestamp.", "format": "date-time", "type": "string"}, "location": map[string]any{"type": "string"}, "start": map[string]any{"description": "RFC3339 start timestamp.", "format": "date-time", "type": "string"}, "summary": map[string]any{"minLength": 1, "type": "string"}, "time_zone": map[string]any{"description": "Optional IANA time zone.", "type": "string"}}, "required": []any{"summary", "start", "end"}, "type": "object"})

var toolOutputSchema = schema.JSONSchema(map[string]any{"properties": map[string]any{"attendees": map[string]any{"items": map[string]any{"properties": map[string]any{"email": map[string]any{"type": "string"}, "response_status": map[string]any{"type": "string"}}, "type": "object"}, "type": "array"}, "end": map[string]any{"type": "string"}, "event_id": map[string]any{"type": "string"}, "html_link": map[string]any{"type": "string"}, "start": map[string]any{"type": "string"}, "status": map[string]any{"type": "string"}, "summary": map[string]any{"type": "string"}}, "type": "object"})
