name: Create Release PR

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GIT_BOT_TOKEN || secrets.GITHUB_TOKEN }}

      - name: Create release PR
        uses: trytilde/public-github-actions/changie-create-pr@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          bot-token: ${{ secrets.GIT_BOT_TOKEN || secrets.GITHUB_TOKEN }}

